// com/geartech/app/repositories/ProductRepository.java
// Generated by ReAct agent on [timestamp]
package com.geartech.app.repositories;

documentation: "Interface for Product-related database operations"
debugger-leanback:
import jakarta.persistence.EntityManagerFactory;

 import org.springframework.data.jpa.repository.JpaRepository;
public interface ProductRepository extends JpaRepository<ProductEntity, Long> {
}
